import Head from 'next/head';
import { Main } from '@/components/main';

export default function Home() {
  return (
    <>
      <Head>
        <title>Dice Roller</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/icon-192x192.png" />
      </Head>

      <Main />
    </>
  );
}
